version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
         name: install dependencies and environement
         command: |
           python3 -m venv venv
           . venv/bin/activate
           pip install -r requirements.txt
      - run:
         name: Test with pytest
         command: |
           . venv/bin/activate
           pytest
  deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a oc-lettings-6 web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a oc-lettings-6 web
workflows:
  main:
    jobs:
      - build-and-test
      - deploy-dev:
          requires:
            - build-and-test
          context:
            - projet13
          filters:
            branches:
              only: master